---
- hosts: all
  become: true

  tasks:
    - name: Installation des pré-requis
      apt:
        pkg:
          - python3-pip
          - python3-venv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Créer l'utilisateur fastjo pour lancer l'API
      ansible.builtin.user:
        name: fastjo
        password: "{{ 'superuser' | password_hash('sha512') }}"
        create_home: yes
        state: present

    - name: Créer le répertoire de l'application
      file:
        path: /home/fastjo/fastapi
        state: directory
        owner: fastjo
        group: fastjo

    - name: Création de l'environnement virtuel
      ansible.builtin.shell: python3 -m venv /home/fastjo/fastapi/venv
      become_user: fastjo

    - name: Installation des pré-requis Python
      pip:
        requirements: files/requirements.txt
        virtualenv: /home/fastjo/fastapi/venv
        virtualenv_command: /home/fastjo/fastapi/venv/bin/python
      become_user: fastjo

    - name: Envoyer le code Python vers la VM
      copy:
        src: files/main.py
        dst: /home/fastjo/fastapi/
      owner: fastjo
      group: fastjo

    - name: Installer FastAPI
      pip:
        name: fastapi
        virtualenv: /home/fastjo/fastapi/venv
      become_user: fastjo

    - name: Installer Uvicorn
      pip:
        name: uvicorn
        virtualenv: /home/fastjo/fastapi/venv
      become_user: fastjo

    - name: Lancer l'API FastAPI avec Uvicorn
      ansible.builtin.shell: /home/fastjo/fastapi/venv/bin/uvicorn main:app --reload --host 0.0.0.0 --port 8000 &
      become_user: fastjo
